version: '3.1'

services:
  backend:
    build: .
    container_name: trivia_backend
    ports:
      - 3001:3001 # porta padrão da aplicação
      - 9229:9229 # porta para debugging
    command: npm run dev # roda aplicação com nodemon
    volumes:
      # vincula pasta local com a dentro do container
      - ./:/app
    environment:
      DB_USER: root
      DB_PASS: senha_mysql
      DB_HOST: db
      DB_PORT: 3306
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.29
    container_name: trivia_db
    environment:
      MYSQL_ROOT_PASSWORD: senha_mysql
      MYSQL_DATABASE: Trivia
    ports:
      - 3306:3306
    healthcheck:
      # Deve aguardar o banco ficar operacional
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    volumes:
      # adiciona scripts SQL para serem executados ao iniciar a DB
      - ./sql:/docker-entrypoint-initdb.d
